.. External links for use project-wide are configured here.
.. _LMS7002M transceiver datasheet: https://cdn.sanity.io/files/yv2p7ubm/production/dc7fec4c445b008b9a1d35ea5a16a2850e923fe2.pdf
.. _XC7A50T-2CPG236I: https://docs.xilinx.com/v/u/en-US/ds181_Artix_7_Data_Sheet
.. _Microchip USB3333E-GL: https://ww1.microchip.com/downloads/aemDocuments/documents/OTH/ProductDocuments/DataSheets/00001880A.pdf

